name: Deploy
on:
  push:
    branches:
      nonplanar

env:
  LDLOADLIBS: -lstdc++
  SLIC3R_STATIC: 1
  SLIC3R_VERSION: 1.3.0
  BOOST_DIR: C:\dev\boost_1_63_0
  WXDIR: C:\dev\wxwidgets
  WXSHARED: SHARED=0
  FORCE_WX_BUILD: 0
  FORCE_BOOST_REINSTALL: 0
  ARCH: 64bit

jobs:
  github_build:
    name: Build
    strategy:
      fail-fast: false

    runs-on: windows-2022
    continue-on-error: true
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.5

      - name: Setup | Install Deps
        run: |
          choco install wget --no-progress
          package/win/appveyor_preinstall.ps1

      - name: Build | Build
        run: |
          package/win/appveyor_buildscript.ps1

      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: slic3r-dev
          path: slic3r*zip
      - name: Build | Publish
        uses: softprops/action-gh-release@v1
        with:
          files: slic3r*zip